name = "server"
main = "src/index.ts"
compatibility_date = "2024-10-26"
compatibility_flags = [ "nodejs_compat" ]

 [vars]


# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1